import type { GuideCard, GuideSection, GuideSectionId } from './guide-data';

export type CourseLanguage = 'ru' | 'kk' | 'en';

type CardText = Omit<GuideCard, 'id'>;
type SectionText = Pick<GuideSection, 'short' | 'title' | 'principle'>;

const card = (title: string, label: string, signal: string, steps: string[], trap: string, check: string): CardText => ({
  title, label, signal, steps, trap, check,
});

const sections: Record<GuideSectionId, Record<CourseLanguage, SectionText>> = {
  listening: {
    ru: { short: 'L', title: 'Listening', principle: 'Слушай запись и ищи точный ответ. Не нужно понимать каждое слово. Следи за номером вопроса и за словами с тем же смыслом.' },
    kk: { short: 'L', title: 'Listening', principle: 'Жазбаны тыңдап, нақты жауапты тап. Әр сөзді түсіну міндетті емес. Сұрақ нөмірін және мағынасы ұқсас сөздерді бақыла.' },
    en: { short: 'L', title: 'Listening', principle: 'Listen for the exact answer. You do not need every word. Follow the question number and listen for words with the same meaning.' },
  },
  reading: {
    ru: { short: 'R', title: 'Reading', principle: 'Каждый ответ нужно доказать строкой из текста. Не отвечай только по памяти или по одному похожему слову.' },
    kk: { short: 'R', title: 'Reading', principle: 'Әр жауапты мәтіндегі жолмен дәлелде. Тек есіңе немесе бір ұқсас сөзге сүйеніп жауап берме.' },
    en: { short: 'R', title: 'Reading', principle: 'Prove every answer with a line from the text. Do not answer from memory or from one matching word.' },
  },
  writing: {
    ru: { short: 'W', title: 'Writing', principle: 'Сначала дай ясный ответ. Потом объясни его простыми словами и добавь пример. Точное простое слово лучше редкого слова с ошибкой.' },
    kk: { short: 'W', title: 'Writing', principle: 'Алдымен анық жауап бер. Кейін оны қарапайым сөзбен түсіндіріп, мысал қос. Қатесі бар сирек сөзден дәл әрі оңай сөз жақсы.' },
    en: { short: 'W', title: 'Writing', principle: 'Give a clear answer first. Explain it in simple words and add an example. A correct simple word is better than a rare word used wrongly.' },
  },
  speaking: {
    ru: { short: 'S', title: 'Speaking', principle: 'Отвечай прямо, скажи почему и добавь деталь или пример. Говори спокойно. Здесь проверяют твой английский, а не знания о мире.' },
    kk: { short: 'S', title: 'Speaking', principle: 'Тура жауап бер, себебін айт, сосын бір мысал не қосымша мәлімет қос. Асықпай сөйле. Мұнда әлем туралы білімің емес, ағылшын тілің тексеріледі.' },
    en: { short: 'S', title: 'Speaking', principle: 'Answer directly, say why, and add one detail or example. Speak calmly. The test checks your English, not your knowledge of the world.' },
  },
};

const cards: Record<string, Record<CourseLanguage, CardText>> = {
  'l-master': {
    ru: card('Главный план', 'До · во время · после', 'Используй этот план в любой части Listening.', ['До записи прочитай правило о числе слов и подчеркни главные слова.', 'Предскажи вид ответа: имя, число, место или причина.', 'Во время записи следи за номерами. Пропустил ответ — сразу иди дальше.', 'После записи проверь написание, окончание -s и число слов.'], 'Первое услышанное слово может быть исправлено позже.', 'Ты знаешь причину каждой ошибки: не услышал, потерял место, не узнал смысл или неверно написал.'),
    kk: card('Негізгі жоспар', 'Дейін · тыңдау кезінде · кейін', 'Бұл жоспарды Listening-тің кез келген бөлімінде қолдан.', ['Жазбаға дейін сөз саны туралы ережені оқып, негізгі сөздерді белгіле.', 'Жауаптың түрін болжа: адам аты, сан, орын немесе себеп.', 'Жазба кезінде сұрақ нөмірін бақыла. Бір жауапты өткізіп алсаң, бірден келесіге өт.', 'Соңында жазылуын, -s жалғауын және сөз санын тексер.'], 'Алғаш естіген сөз кейін түзетілуі мүмкін.', 'Әр қатенің себебін айта аласың: естімедім, орынды жоғалттым, мағынаны танымадым немесе қате жаздым.'),
    en: card('Main plan', 'Before · during · after', 'Use this plan in every Listening part.', ['Before the audio, read the word limit and mark the key words.', 'Predict the answer type: a name, number, place, or reason.', 'Follow the question numbers. If you miss one answer, move on at once.', 'At the end, check spelling, final -s, and the word limit.'], 'The first answer you hear may be corrected later.', 'You can name the reason for every mistake: sound, place, meaning, or spelling.'),
  },
  'l-completion': {
    ru: card('Заполнение пропусков', 'Предложения · заметки · формы', 'В задании есть пустые места и точный лимит слов.', ['Обведи лимит: например, NO MORE THAN TWO WORDS.', 'Посмотри на слова до и после пропуска. Они покажут нужную форму.', 'Запиши слова из аудио без лишних слов.', 'Прочитай готовую фразу целиком и проверь, звучит ли она правильно.'], 'Верный смысл не поможет, если ответ не подходит по форме или слишком длинный.', 'Ответ подходит к предложению, написан верно и не нарушает лимит.'),
    kk: card('Бос орынды толтыру', 'Сөйлем · жазба · форма', 'Тапсырмада бос орын және нақты сөз шегі бар.', ['NO MORE THAN TWO WORDS сияқты шекті дөңгелекте.', 'Бос орынның алдындағы және кейінгі сөздерді оқы. Олар жауаптың түрін көрсетеді.', 'Аудиодан естіген сөзді артық сөзсіз жаз.', 'Дайын сөйлемді толық оқып, дұрыс естілетінін тексер.'], 'Мағына дұрыс болса да, жауаптың түрі не ұзындығы қате болуы мүмкін.', 'Жауап сөйлемге сай, дұрыс жазылған және сөз шегінен аспайды.'),
    en: card('Fill the gaps', 'Sentences · notes · forms', 'The task has gaps and an exact word limit.', ['Circle the limit, such as NO MORE THAN TWO WORDS.', 'Read the words before and after the gap. They show the needed form.', 'Write the words from the audio without extra words.', 'Read the full sentence and check that it sounds right.'], 'The meaning may be right, but the form or word count may still be wrong.', 'The answer fits the sentence, is spelled correctly, and follows the limit.'),
  },
  'l-mcq': {
    ru: card('Выбор A, B или C', 'Multiple choice', 'В записи обычно звучат все варианты.', ['До записи найди разницу между A, B и C.', 'Сократи каждый вариант до одной главной идеи.', 'Отмечай услышанные варианты, но жди конца мысли.', 'Выбери ответ и скажи, почему два других не подходят.'], 'Слово из варианта может прозвучать рядом с неверной идеей.', 'Ты можешь объяснить выбор одним коротким предложением.'),
    kk: card('A, B немесе C таңдау', 'Multiple choice', 'Жазбада барлық нұсқа айтылуы мүмкін.', ['Жазбаға дейін A, B және C арасындағы айырманы тап.', 'Әр нұсқаны бір негізгі ойға қысқарт.', 'Естіген нұсқаларды белгіле, бірақ ой аяқталғанша күт.', 'Жауапты таңдап, қалған екеуі неге келмейтінін айт.'], 'Нұсқадағы сөз қате ойдың жанында айтылуы мүмкін.', 'Таңдауыңды бір қысқа сөйлеммен түсіндіре аласың.'),
    en: card('Choose A, B, or C', 'Multiple choice', 'The audio may mention every option.', ['Find the difference between A, B, and C before the audio.', 'Shorten each option to one main idea.', 'Mark options you hear, but wait for the full idea.', 'Choose the answer and say why the other two are wrong.'], 'A word from an option may appear next to the wrong idea.', 'You can explain your choice in one short sentence.'),
  },
  'l-map': {
    ru: card('Карта или план', 'Map / plan labelling', 'Нужно найти места по маршруту.', ['Найди старт, вход, компас и уже подписанные места.', 'До записи глазами пройди возможный путь.', 'Во время записи двигай пальцем по карте.', 'Если потерял место, найди следующий известный ориентир и продолжай.'], 'Left и right зависят от направления движения, а не от твоего взгляда.', 'Все точки стоят по пути в том же порядке, что и в записи.'),
    kk: card('Карта немесе жоспар', 'Map / plan labelling', 'Бағыт бойынша орындарды табу керек.', ['Бастау нүктесін, кіреберісті, компасты және дайын атауларды тап.', 'Жазбаға дейін ықтимал жолды көзіңмен қарап шық.', 'Тыңдап отырып, саусағыңды карта бойымен жылжыт.', 'Жолдан адассаң, келесі таныс орынды тауып жалғастыр.'], 'Left пен right сенің қараған жағыңа емес, қозғалыс бағытына байланысты.', 'Барлық нүкте аудиодағы ретпен жолдың бойында тұр.'),
    en: card('Map or plan', 'Map / plan labelling', 'Find places by following a route.', ['Find the start, entrance, compass, and named places.', 'Trace a possible route with your eyes before the audio.', 'Move your finger along the map while you listen.', 'If you get lost, find the next known place and continue.'], 'Left and right follow the speaker’s direction, not your view of the page.', 'Every point is on a possible route and follows the audio order.'),
  },
  'l-diagram': {
    ru: card('Схема предмета', 'Diagram labelling', 'Стрелки указывают на части предмета или процесса.', ['Посмотри, что уже подписано и куда ведут стрелки.', 'Реши, нужен материал, название части, место или действие.', 'Слушай слова места: under, inside, at the top, next to.', 'Проверь, что ответ относится точно к концу стрелки.'], 'Описание может говорить о работе детали, а не о её виде.', 'Каждый ответ называет именно ту часть, куда ведёт линия.'),
    kk: card('Заттың сызбасы', 'Diagram labelling', 'Сызықтар заттың не үдерістің бөліктерін көрсетеді.', ['Дайын атауларды және сызықтардың қайда барғанын қара.', 'Материал, бөлік атауы, орын немесе әрекет керек пе — анықта.', 'Under, inside, at the top, next to сияқты орын сөздерін тыңда.', 'Жауап сызықтың дәл соңындағы бөлікке қатысты екенін тексер.'], 'Сипаттама бөлшектің көрінісін емес, қызметін айтуы мүмкін.', 'Әр жауап сызық көрсеткен нақты бөлікті атайды.'),
    en: card('Object diagram', 'Diagram labelling', 'Lines point to parts of an object or process.', ['Check the labels already given and where each line ends.', 'Decide if you need a material, part, place, or action.', 'Listen for place words: under, inside, at the top, next to.', 'Make sure the answer names the exact point of the line.'], 'The audio may describe what a part does, not what it looks like.', 'Every answer names the exact part shown by the line.'),
  },
  'l-table': {
    ru: card('Таблица', 'Table completion', 'Ответ должен подходить и к строке, и к столбцу.', ['Прочитай названия строк и столбцов.', 'Пойми, в каком порядке идёт информация.', 'Сравни готовые клетки, чтобы увидеть форму ответа.', 'После записи прочитай каждую клетку вместе с её заголовками.'], 'Слово может относиться к соседней строке.', 'Ответ подходит сразу к двум заголовкам таблицы.'),
    kk: card('Кесте', 'Table completion', 'Жауап жолға да, бағанға да сай болуы керек.', ['Жолдар мен бағандардың атауын оқы.', 'Ақпарат қай ретпен берілетінін түсін.', 'Жауаптың түрін білу үшін дайын ұяшықтарды салыстыр.', 'Соңында әр ұяшықты екі атауымен бірге оқы.'], 'Естіген сөз көрші жолға қатысты болуы мүмкін.', 'Жауап кестенің екі атауына да сай келеді.'),
    en: card('Table', 'Table completion', 'An answer must fit both its row and its column.', ['Read the row and column headings.', 'Work out the order of the information.', 'Use filled cells to see the needed answer form.', 'Read each final cell with both of its headings.'], 'A word you hear may belong to the next row.', 'The answer fits both table headings.'),
  },
  'l-short': {
    ru: card('Короткий ответ', 'Short answer', 'Нужно ответить несколькими словами.', ['Подчеркни вопросительное слово: who, where, why или how many.', 'Предскажи вид ответа и нужную единицу.', 'Запиши только ответ, не переписывай вопрос.', 'Проверь число слов и окончание множественного числа.'], 'Лишнее верное слово всё равно может нарушить лимит.', 'Ответ прямо отвечает на вопрос и не содержит лишних слов.'),
    kk: card('Қысқа жауап', 'Short answer', 'Бірнеше сөзбен жауап беру керек.', ['Who, where, why немесе how many сияқты сұрақ сөзін белгіле.', 'Жауаптың түрін және өлшем бірлігін болжа.', 'Сұрақты көшірмей, тек жауапты жаз.', 'Сөз санын және көптік жалғауын тексер.'], 'Артық дұрыс сөздің өзі шектен асыруы мүмкін.', 'Жауап сұраққа тура жауап береді және артық сөзі жоқ.'),
    en: card('Short answer', 'Short answer', 'Answer with only a few words.', ['Mark the question word: who, where, why, or how many.', 'Predict the answer type and any needed unit.', 'Write only the answer; do not copy the question.', 'Check the word count and plural ending.'], 'One extra correct word can still break the limit.', 'The answer directly answers the question and has no extra words.'),
  },
  'l-part4': {
    ru: card('Длинная лекция', 'Listening Part 4', 'Один человек говорит долго и почти без пауз.', ['Быстро просмотри все вопросы и раздели их на темы.', 'Подчеркни слова, которые показывают переход: first, however, next.', 'Следи за номерами и не жди пропущенный ответ.', 'После записи проверь форму всех слов.'], 'Если ждать старый ответ, можно потерять ещё несколько.', 'Ты замечаешь слова перехода и знаешь, где начинается новый ответ.'),
    kk: card('Ұзақ дәріс', 'Listening Part 4', 'Бір адам ұзақ сөйлейді және үзіліс аз болады.', ['Барлық сұрақты тез қарап, тақырыптарға бөл.', 'First, however, next сияқты ауысу сөздерін белгіле.', 'Нөмірлерді бақыла және өткізіп алған жауапты күтпе.', 'Соңында барлық сөздің түрін тексер.'], 'Өткен жауапты күте берсең, тағы бірнеше жауаптан айырыласың.', 'Ауысу сөздерін естіп, жаңа жауаптың қайда басталғанын білесің.'),
    en: card('Long lecture', 'Listening Part 4', 'One person speaks for a long time with few pauses.', ['Scan all questions and split them into topic groups.', 'Mark change words such as first, however, and next.', 'Follow the numbers and do not wait for a missed answer.', 'Check the form of every final word.'], 'Waiting for one missed answer can make you lose several more.', 'You hear the change words and know when a new answer starts.'),
  },

  'r-master': {
    ru: card('Главный план', '60 минут · 3 текста', 'Используй этот план для полного Reading.', ['Сначала прочитай задание и найди главные слова.', 'Найди нужное место в тексте по имени, числу или редкому слову.', 'Сравни весь смысл вопроса и строки, а не одно слово.', 'Запиши ответ точно в нужной форме и следи за временем.'], 'Похожее слово ещё не доказывает ответ.', 'Для каждого ответа ты можешь показать строку-доказательство.'),
    kk: card('Негізгі жоспар', '60 минут · 3 мәтін', 'Бұл жоспарды толық Reading үшін қолдан.', ['Алдымен тапсырманы оқып, негізгі сөздерді тап.', 'Мәтіндегі орынды адам аты, сан немесе сирек сөз арқылы тап.', 'Бір сөзді емес, сұрақ пен жолдың толық мағынасын салыстыр.', 'Жауапты керек түрде жазып, уақытты бақыла.'], 'Ұқсас сөз жауапты әлі дәлелдемейді.', 'Әр жауап үшін дәлел болатын жолды көрсете аласың.'),
    en: card('Main plan', '60 minutes · 3 texts', 'Use this plan for a full Reading test.', ['Read the task first and mark its key words.', 'Find the area in the text with a name, number, or rare word.', 'Compare the full meaning, not just one word.', 'Write the answer in the exact form and watch the time.'], 'A matching word does not prove an answer.', 'You can point to one line of proof for every answer.'),
  },
  'r-headings': {
    ru: card('Заголовки абзацев', 'Matching headings', 'Нужно выбрать главную мысль каждого абзаца.', ['Прочитай первое и последнее предложение абзаца.', 'Скажи смысл абзаца своими простыми словами.', 'Убери заголовки, которые подходят только к одной детали.', 'Выбери заголовок, который покрывает почти весь абзац.'], 'Яркий пример может быть деталью, а не главной мыслью.', 'Заголовок подходит большей части абзаца.'),
    kk: card('Абзац тақырыптары', 'Matching headings', 'Әр абзацтың негізгі ойын таңдау керек.', ['Абзацтың бірінші және соңғы сөйлемін оқы.', 'Абзацтың ойын өз сөзіңмен қысқа айт.', 'Тек бір ұсақ мәліметке сай тақырыптарды алып таста.', 'Абзацтың көп бөлігіне сай тақырыпты таңда.'], 'Есте қаларлық мысал негізгі ой болмауы мүмкін.', 'Тақырып абзацтың көп бөлігіне сай келеді.'),
    en: card('Paragraph headings', 'Matching headings', 'Choose the main idea of each paragraph.', ['Read the first and last sentence.', 'Say the paragraph idea in your own simple words.', 'Remove headings that fit only one small detail.', 'Choose the heading that covers most of the paragraph.'], 'A strong example may be a detail, not the main idea.', 'The heading fits most of the paragraph.'),
  },
  'r-tfng': {
    ru: card('True / False / Not Given', 'Факт в тексте', 'Сравни утверждение с тем, что прямо сказано.', ['Раздели утверждение на человека, действие, время и количество.', 'Найди место в тексте и сравни каждую часть.', 'TRUE: смысл тот же. FALSE: текст говорит обратное.', 'NOT GIVEN: нужной информации нет.'], 'Если подтверждения нет, это ещё не FALSE.', 'Ты можешь показать совпадение, противоположность или отсутствие данных.'),
    kk: card('True / False / Not Given', 'Мәтіндегі дерек', 'Сөйлемді мәтінде тура айтылған ақпаратпен салыстыр.', ['Сөйлемді адам, әрекет, уақыт және сан бөліктеріне бөл.', 'Мәтіндегі орынды тауып, әр бөлікті салыстыр.', 'TRUE: мағына бірдей. FALSE: мәтін керісінше айтады.', 'NOT GIVEN: керек ақпарат жоқ.'], 'Дәлел жоқ болса, ол бірден FALSE болмайды.', 'Сәйкестікті, қарама-қарсылықты немесе ақпараттың жоқтығын көрсете аласың.'),
    en: card('True / False / Not Given', 'Fact in the text', 'Compare the statement with what the text says.', ['Split the statement into person, action, time, and amount.', 'Find the right place and compare every part.', 'TRUE: same meaning. FALSE: the text says the opposite.', 'NOT GIVEN: the needed information is missing.'], 'No proof does not mean FALSE.', 'You can show the match, the opposite, or the missing information.'),
  },
  'r-ynng': {
    ru: card('Yes / No / Not Given', 'Мнение автора', 'Нужно понять, согласен ли автор.', ['Найди слово мнения: believe, should, important, harmful.', 'Проверь, чьё это мнение: автора или другого человека.', 'YES: автор согласен. NO: автор думает наоборот.', 'NOT GIVEN: мнение автора не ясно.'], 'Автор может привести чужое мнение, а потом спорить с ним.', 'Ответ основан на позиции автора, а не на твоём мнении.'),
    kk: card('Yes / No / Not Given', 'Автордың пікірі', 'Автордың келісетінін не келіспейтінін түсіну керек.', ['Believe, should, important, harmful сияқты пікір сөздерін тап.', 'Бұл кімнің пікірі екенін тексер: автордікі ме, басқа адамдікі ме.', 'YES: автор келіседі. NO: автор керісінше ойлайды.', 'NOT GIVEN: автордың пікірі анық емес.'], 'Автор өзгенің пікірін айтып, кейін онымен келіспеуі мүмкін.', 'Жауап сенің емес, автордың пікіріне сүйенеді.'),
    en: card('Yes / No / Not Given', 'Writer’s view', 'Decide if the writer agrees.', ['Find view words such as believe, should, important, or harmful.', 'Check whose view it is: the writer’s or someone else’s.', 'YES: the writer agrees. NO: the writer thinks the opposite.', 'NOT GIVEN: the writer’s view is not clear.'], 'The writer may give another person’s view and then reject it.', 'Your answer is based on the writer’s view, not your own.'),
  },
  'r-information': {
    ru: card('Где это сказано', 'Matching information', 'Нужно найти абзац с нужной информацией.', ['Подчеркни, что именно нужно: пример, причина, сравнение или имя.', 'Ищи слова с тем же смыслом, а не точную копию.', 'Проверь весь абзац вокруг найденной строки.', 'Помни: один абзац иногда даёт два ответа.'], 'Ответы могут идти не по порядку.', 'В выбранном абзаце есть именно тот вид информации, который просит вопрос.'),
    kk: card('Бұл қай жерде айтылған', 'Matching information', 'Керек ақпараты бар абзацты табу қажет.', ['Не керегін белгіле: мысал, себеп, салыстыру немесе есім.', 'Дәл сол сөзді емес, мағынасы ұқсас сөздерді ізде.', 'Табылған жолдың айналасындағы толық абзацты тексер.', 'Бір абзац кейде екі жауап бере алады.'], 'Жауаптар ретімен келмеуі мүмкін.', 'Таңдалған абзацта сұралған ақпараттың дәл сол түрі бар.'),
    en: card('Where is it said?', 'Matching information', 'Find the paragraph with the needed information.', ['Mark what you need: an example, reason, comparison, or name.', 'Look for the same meaning, not the same words.', 'Check the full paragraph around the line you found.', 'One paragraph may give more than one answer.'], 'The answers may not follow the text order.', 'The chosen paragraph has the exact kind of information asked for.'),
  },
  'r-completion': {
    ru: card('Заполнение пропусков', 'Summary / sentence completion', 'Нужно вставить слова из текста.', ['Обведи лимит слов и реши, какая часть речи нужна.', 'Найди место текста по словам рядом с пропуском.', 'Выбери точные слова из текста и не меняй их форму.', 'Прочитай готовое предложение целиком.'], 'Слово рядом с темой может не подходить по грамматике.', 'Лимит соблюдён, а готовая фраза звучит правильно.'),
    kk: card('Бос орынды толтыру', 'Summary / sentence completion', 'Мәтіндегі сөздерді бос орынға қою керек.', ['Сөз шегін белгіле және қай сөз табы керек екенін анықта.', 'Бос орынның жанындағы сөздер арқылы мәтіндегі орынды тап.', 'Мәтіннен дәл сөздерді алып, түрін өзгертпе.', 'Дайын сөйлемді толық оқы.'], 'Тақырыпқа жақын сөз грамматикаға сай келмеуі мүмкін.', 'Сөз шегі сақталған және дайын сөйлем дұрыс естіледі.'),
    en: card('Fill the gaps', 'Summary / sentence completion', 'Put words from the text into the gaps.', ['Circle the word limit and decide which word type is needed.', 'Use words near the gap to find the right area.', 'Copy the exact text words without changing their form.', 'Read the completed sentence in full.'], 'A word near the topic may not fit the grammar.', 'The word limit is correct and the full sentence works.'),
  },
  'r-mcq': {
    ru: card('Выбор ответа', 'Multiple choice', 'Один вариант точно отвечает на вопрос.', ['Сначала прочитай вопрос без вариантов.', 'Найди нужное место и придумай короткий ответ сам.', 'Сравни свой ответ с A, B, C и D.', 'Убери варианты, которые верны вообще, но не отвечают на вопрос.'], 'Правдивый факт может быть неверным ответом на этот вопрос.', 'Ты можешь доказать выбор и убрать каждый другой вариант.'),
    kk: card('Жауапты таңдау', 'Multiple choice', 'Бір нұсқа сұраққа дәл жауап береді.', ['Алдымен нұсқаларсыз сұрақты оқы.', 'Керек орынды тауып, өзің қысқа жауап ойла.', 'Өз жауабыңды A, B, C және D нұсқаларымен салыстыр.', 'Жалпы дұрыс, бірақ сұраққа жауап бермейтін нұсқаларды алып таста.'], 'Дұрыс дерек осы сұрақтың жауабы болмауы мүмкін.', 'Таңдауыңды дәлелдеп, әр басқа нұсқаны алып тастай аласың.'),
    en: card('Choose the answer', 'Multiple choice', 'One option answers the exact question.', ['Read the question before the options.', 'Find the right area and make your own short answer.', 'Compare your answer with A, B, C, and D.', 'Remove options that are true but do not answer this question.'], 'A true fact can still be the wrong answer.', 'You can prove your choice and remove every other option.'),
  },
  'r-classification': {
    ru: card('Кто, когда или какая группа', 'Matching features', 'Нужно связать факт с человеком, временем или группой.', ['Отметь все имена или группы и их короткие особенности.', 'Найди утверждение в тексте по смыслу.', 'Проверь, кто выполняет действие в этом предложении.', 'Используй букву категории столько раз, сколько разрешено.'], 'Имя может стоять рядом, но идея принадлежать другому человеку.', 'Ты можешь коротко объяснить связь факта и выбранной группы.'),
    kk: card('Кім, қашан немесе қай топ', 'Matching features', 'Деректі адаммен, уақытпен немесе топпен байланыстыру керек.', ['Барлық есім мен топты және олардың қысқа белгісін жаз.', 'Сөйлемді мәтіннен мағынасы арқылы тап.', 'Сол сөйлемде әрекетті кім жасап тұрғанын тексер.', 'Ереже рұқсат етсе, бір әріпті бірнеше рет қолдан.'], 'Есім жақын тұрса да, ой басқа адамға тиесілі болуы мүмкін.', 'Дерек пен топтың байланысын қысқа түсіндіре аласың.'),
    en: card('Who, when, or which group?', 'Matching features', 'Match a fact to a person, time, or group.', ['List each name or group with one short detail.', 'Find the statement in the text by meaning.', 'Check who performs the action in that sentence.', 'Reuse a letter if the instructions allow it.'], 'A nearby name may not own the idea.', 'You can explain the link between the fact and the group.'),
  },
  'r-endings': {
    ru: card('Концы предложений', 'Matching sentence endings', 'Нужно соединить начало и конец предложения.', ['Прочитай начало и предскажи нужный смысл.', 'Убери окончания, которые не подходят по грамматике.', 'Найди доказательство в тексте.', 'Выбери окончание, которое подходит и по смыслу, и по грамматике.'], 'Красивое предложение может не совпадать с текстом.', 'Грамматика и точный смысл совпадают.'),
    kk: card('Сөйлемнің жалғасы', 'Matching sentence endings', 'Сөйлемнің басы мен соңын қосу керек.', ['Сөйлемнің басын оқып, керек мағынаны болжа.', 'Грамматикаға келмейтін жалғастарды алып таста.', 'Мәтіннен дәлел тап.', 'Мағынасы да, грамматикасы да сай жалғасты таңда.'], 'Жақсы естілетін сөйлем мәтінге сай болмауы мүмкін.', 'Грамматика мен нақты мағына бірге сәйкес келеді.'),
    en: card('Sentence endings', 'Matching sentence endings', 'Join each sentence start to the right ending.', ['Read the start and predict the needed meaning.', 'Remove endings that do not fit the grammar.', 'Find proof in the text.', 'Choose the ending that fits both meaning and grammar.'], 'A nice sentence may still disagree with the text.', 'Both grammar and exact meaning match.'),
  },
  'r-visual': {
    ru: card('Таблица, схема или рисунок', 'Visual completion', 'Нужно перенести данные текста в готовую схему.', ['Пойми, как устроена схема и куда идёт движение.', 'Реши, какой вид слова нужен в каждом месте.', 'Найди нужный этап в тексте.', 'Проверь порядок и лимит слов.'], 'Несколько предложений могут описывать один этап.', 'Ответ подходит по месту, смыслу и порядку.'),
    kk: card('Кесте, сызба немесе сурет', 'Visual completion', 'Мәтіндегі деректі дайын сызбаға көшіру керек.', ['Сызбаның құрылымын және бағытын түсін.', 'Әр орынға қандай сөз түрі керек екенін анықта.', 'Мәтіннен сол кезеңді тап.', 'Ретін және сөз шегін тексер.'], 'Бір кезең бірнеше сөйлеммен сипатталуы мүмкін.', 'Жауап орнына, мағынасына және ретіне сай.'),
    en: card('Table, flow chart, or picture', 'Visual completion', 'Move information from the text into a visual plan.', ['Understand the visual order and direction.', 'Decide which word type each gap needs.', 'Find that step in the text.', 'Check the order and word limit.'], 'Several sentences may describe one step.', 'The answer fits the place, meaning, and order.'),
  },
  'r-short-title': {
    ru: card('Короткий ответ или название', 'Answer / title', 'Дай точный ответ или выбери название всего текста.', ['Для короткого ответа отметь вопросительное слово и лимит.', 'Найди доказательство и возьми только нужные слова.', 'Для названия скажи общую тему и цель текста.', 'Не выбирай название только по одному яркому примеру.'], 'Самая интересная деталь редко описывает весь текст.', 'Ответ короткий и точный, а название подходит всему тексту.'),
    kk: card('Қысқа жауап немесе атау', 'Answer / title', 'Нақты жауап бер немесе бүкіл мәтінге атау таңда.', ['Қысқа жауап үшін сұрақ сөзін және сөз шегін белгіле.', 'Дәлелді тауып, тек керек сөздерді ал.', 'Атау үшін мәтіннің жалпы тақырыбы мен мақсатын айт.', 'Бір қызық мысалға ғана қарап атау таңдама.'], 'Ең қызық мәлімет бүкіл мәтінді сипаттамауы мүмкін.', 'Жауап қысқа әрі нақты, ал атау бүкіл мәтінге сай.'),
    en: card('Short answer or title', 'Answer / title', 'Give an exact answer or choose a title for the whole text.', ['For a short answer, mark the question word and word limit.', 'Find proof and take only the needed words.', 'For a title, state the whole text’s topic and purpose.', 'Do not choose a title from one strong example.'], 'The most interesting detail rarely covers the whole text.', 'The answer is short and exact, and the title fits the full text.'),
  },

  'w-t1-master': {
    ru: card('Task 1 за 20 минут', '150 слов или больше', 'Опиши главные данные без своего мнения.', ['За 3 минуты найди 2–3 главные особенности.', 'Напиши вступление своими словами и общий вывод без цифр.', 'Сгруппируй данные в два абзаца и добавь точные сравнения.', 'Оставь 2 минуты на числа, слова и 150 слов.'], 'Не придумывай причины, которых нет на картинке.', 'Есть вступление, общий вывод, два абзаца и точные данные.'),
    kk: card('Task 1: 20 минут', '150 сөз немесе көп', 'Негізгі деректерді өз пікіріңсіз сипатта.', ['3 минутта 2–3 басты ерекшелікті тап.', 'Кіріспені өз сөзіңмен және сансыз жалпы қорытынды жаз.', 'Деректерді екі абзацқа бөліп, нақты салыстыр.', 'Сандарды, сөздерді және 150 сөзді тексеруге 2 минут қалдыр.'], 'Суретте жоқ себептерді ойдан қоспа.', 'Кіріспе, жалпы қорытынды, екі абзац және нақты дерек бар.'),
    en: card('Task 1 in 20 minutes', '150 words or more', 'Describe the main data without your opinion.', ['Use 3 minutes to find 2–3 main features.', 'Write the opening in your words and an overview without numbers.', 'Group the data into two paragraphs and add exact comparisons.', 'Keep 2 minutes to check numbers, words, and the 150-word limit.'], 'Do not invent reasons that the visual does not show.', 'You have an opening, overview, two paragraphs, and correct data.'),
  },
  'w-line': {
    ru: card('Линейный график', 'Изменения со временем', 'Покажи направление линий и главные сравнения.', ['Найди начало, конец, самый высокий и самый низкий результат.', 'Сгруппируй линии с похожим движением.', 'В общем выводе напиши только главные направления.', 'В абзацах сравни важные точки, а не перечисляй все числа.'], 'Список всех чисел скрывает главную картину.', 'Читатель видит направление каждой линии и важные сравнения.'),
    kk: card('Сызықтық график', 'Уақыт бойынша өзгеріс', 'Сызықтардың бағытын және басты салыстыруларды көрсет.', ['Басталуын, соңын, ең жоғары және ең төмен нәтижені тап.', 'Қозғалысы ұқсас сызықтарды бірге топтастыр.', 'Жалпы қорытындыда тек басты бағыттарды жаз.', 'Абзацтарда маңызды нүктелерді салыстыр, барлық санды тізбе.'], 'Барлық санды жазу негізгі көріністі жасырады.', 'Оқырман әр сызықтың бағытын және маңызды салыстыруды көреді.'),
    en: card('Line graph', 'Change over time', 'Show each line’s direction and the main comparisons.', ['Find the start, end, highest, and lowest points.', 'Group lines that move in a similar way.', 'Put only the main directions in the overview.', 'Compare key points; do not list every number.'], 'A list of every number hides the main picture.', 'The reader can see each direction and the key comparisons.'),
  },
  'w-bar-table': {
    ru: card('Столбцы или таблица', 'Категории и числа', 'Сравни самые важные группы.', ['Проверь единицы, годы и названия групп.', 'Найди самые большие, маленькие и близкие числа.', 'Собери похожие группы в один абзац.', 'Используй точные сравнения: выше, ниже, вдвое больше.'], 'Не сравнивай числа с разными единицами как одинаковые.', 'У каждого абзаца есть ясная группа и настоящие сравнения.'),
    kk: card('Бағандар немесе кесте', 'Топтар мен сандар', 'Ең маңызды топтарды салыстыр.', ['Өлшемді, жылды және топ атауларын тексер.', 'Ең үлкен, ең кіші және жақын сандарды тап.', 'Ұқсас топтарды бір абзацқа жина.', 'Нақты салыстыр: жоғары, төмен, екі есе көп.'], 'Өлшемі бөлек сандарды бірдей етіп салыстырма.', 'Әр абзацта анық топ және шын салыстыру бар.'),
    en: card('Bar chart or table', 'Groups and numbers', 'Compare the most important groups.', ['Check the units, years, and group names.', 'Find the highest, lowest, and close values.', 'Put similar groups in one paragraph.', 'Use exact comparisons: higher, lower, or twice as much.'], 'Do not compare different units as if they were the same.', 'Each paragraph has a clear group and real comparisons.'),
  },
  'w-pie': {
    ru: card('Круговые диаграммы', 'Части целого', 'Сравни самые большие части и изменения.', ['Проверь, что показывает каждый круг и равна ли сумма 100%.', 'Найди самые большие и маленькие части.', 'Если кругов несколько, сравни рост и падение.', 'Группируй близкие части и используй точные проценты.'], 'Рост с 20% до 30% — это плюс 10 процентных пунктов.', 'Проценты и направления не спорят с диаграммой.'),
    kk: card('Дөңгелек диаграммалар', 'Бүтіннің бөліктері', 'Ең үлкен бөліктер мен өзгерістерді салыстыр.', ['Әр шеңбер нені көрсететінін және қосындысы 100% екенін тексер.', 'Ең үлкен және ең кіші бөліктерді тап.', 'Бірнеше шеңбер болса, өсу мен азаюды салыстыр.', 'Жақын бөліктерді топтастырып, нақты пайыз жаз.'], '20%-дан 30%-ға өсу — 10 пайыздық тармақ.', 'Пайыздар мен бағыттар диаграммаға сай.'),
    en: card('Pie charts', 'Parts of a whole', 'Compare the largest parts and the changes.', ['Check what each circle shows and whether it totals 100%.', 'Find the largest and smallest parts.', 'With several charts, compare rises and falls.', 'Group close parts and use exact percentages.'], 'A rise from 20% to 30% is 10 percentage points.', 'The percentages and directions match the charts.'),
  },
  'w-map': {
    ru: card('Карты места', 'Что изменилось', 'Опиши место до и после изменений.', ['Отметь стороны света и главные части карты.', 'Составь список: добавили, убрали, перенесли, заменили.', 'В общем выводе назови самое большое изменение.', 'Группируй детали по месту, а не по случайному порядку.'], 'Не объясняй, зачем сделали изменение, если карта этого не показывает.', 'Каждое изменение имеет ясное место.'),
    kk: card('Орын карталары', 'Не өзгерді', 'Өзгеріске дейінгі және кейінгі орынды сипатта.', ['Бағыттарды және картаның басты бөліктерін белгіле.', 'Қосылды, алынды, көшірілді, ауыстырылды деген тізім жаса.', 'Жалпы қорытындыда ең үлкен өзгерісті айт.', 'Мәліметті кездейсоқ емес, орны бойынша топтастыр.'], 'Карта көрсетпесе, өзгерістің себебін ойдан қоспа.', 'Әр өзгерістің нақты орны бар.'),
    en: card('Maps of a place', 'What changed', 'Describe the place before and after changes.', ['Mark directions and the main map areas.', 'List what was added, removed, moved, or replaced.', 'Name the biggest change in the overview.', 'Group details by place, not in a random order.'], 'Do not invent why a change happened.', 'Every change has a clear place.'),
  },
  'w-process': {
    ru: card('Схема процесса', 'Этапы по порядку', 'Объясни, как что-то делают или как оно происходит.', ['Найди первый и последний этап и направление стрелок.', 'Раздели процесс на 2–3 понятные части.', 'В общем выводе напиши число этапов и общий путь.', 'Опиши каждый этап по порядку простыми глаголами.'], 'Не добавляй время, причину или детали, которых нет на схеме.', 'Ни один этап не пропущен, и порядок понятен.'),
    kk: card('Үдеріс сызбасы', 'Кезеңдер ретімен', 'Бір нәрсенің қалай жасалатынын не болатынын түсіндір.', ['Бірінші және соңғы кезеңді, жебе бағытын тап.', 'Үдерісті 2–3 түсінікті бөлікке бөл.', 'Жалпы қорытындыда кезең санын және жалпы жолды жаз.', 'Әр кезеңді ретімен, оңай етістіктермен сипатта.'], 'Сызбада жоқ уақытты, себепті не бөлшекті қоспа.', 'Еш кезең қалмаған және реті түсінікті.'),
    en: card('Process diagram', 'Steps in order', 'Explain how something is made or happens.', ['Find the first and last steps and follow the arrows.', 'Split the process into 2–3 clear groups.', 'State the number of stages and the main path in the overview.', 'Describe every step in order with simple verbs.'], 'Do not add time, reasons, or details not shown.', 'No step is missing and the order is clear.'),
  },
  'w-combined': {
    ru: card('Два вида данных', 'Mixed charts', 'Свяжи две картинки в один ответ.', ['Пойми тему, единицы и время каждой картинки.', 'Найди по одной главной особенности в каждой.', 'Ищи связь между двумя наборами данных.', 'В общем выводе упомяни обе картинки, затем сгруппируй детали.'], 'Не пиши два отдельных ответа без общей картины.', 'Обе картинки есть в общем выводе и в абзацах.'),
    kk: card('Екі түрлі дерек', 'Mixed charts', 'Екі суретті бір жауапқа байланыстыр.', ['Әр суреттің тақырыбын, өлшемін және уақытын түсін.', 'Әрқайсысынан бір басты ерекшелік тап.', 'Екі дерек тобының байланысын ізде.', 'Жалпы қорытындыда екеуін де атап, кейін мәліметті топтастыр.'], 'Ортақ көрініссіз екі бөлек жауап жазба.', 'Екі сурет те жалпы қорытындыда және абзацтарда бар.'),
    en: card('Two kinds of data', 'Mixed charts', 'Connect two visuals in one answer.', ['Understand each visual’s topic, unit, and time.', 'Find one main feature in each.', 'Look for a link between the two data sets.', 'Mention both in the overview, then group the details.'], 'Do not write two separate answers with no shared picture.', 'Both visuals appear in the overview and body paragraphs.'),
  },
  'w-t2-master': {
    ru: card('Task 2 за 40 минут', '250 слов или больше', 'Ответь на все части вопроса и держи одну позицию.', ['За 5 минут подчеркни вопросы и запиши свою позицию.', 'Выбери две сильные идеи: по одной на каждый основной абзац.', 'Объясни каждую идею и добавь подходящий пример.', 'Оставь 5 минут на проверку предложений и 250 слов.'], 'Хороший английский не спасёт текст, который не ответил на вопрос.', 'Все части задания имеют ответ, а позиция не меняется.'),
    kk: card('Task 2: 40 минут', '250 сөз немесе көп', 'Сұрақтың барлық бөлігіне жауап бер және бір пікірді ұстан.', ['5 минутта сұрақтарды белгілеп, өз пікіріңді жаз.', 'Екі мықты ой таңда: әр негізгі абзацқа бір ой.', 'Әр ойды түсіндіріп, лайық мысал қос.', 'Сөйлемдер мен 250 сөзді тексеруге 5 минут қалдыр.'], 'Сұраққа жауап бермеген мәтінді жақсы ағылшын тілі құтқармайды.', 'Тапсырманың барлық бөлігіне жауап бар және пікір өзгермейді.'),
    en: card('Task 2 in 40 minutes', '250 words or more', 'Answer every part and keep one clear position.', ['Use 5 minutes to mark the questions and write your position.', 'Choose two strong ideas, one for each body paragraph.', 'Explain each idea and add a fitting example.', 'Keep 5 minutes to check sentences and the 250-word limit.'], 'Good English cannot save an essay that misses the question.', 'Every task part is answered and your position stays the same.'),
  },
  'w-opinion': {
    ru: card('Эссе с мнением', 'Agree / disagree', 'Сразу скажи, согласен ты или нет.', ['Выбери позицию: полностью, частично или не согласен.', 'Напиши эту позицию во вступлении простыми словами.', 'Каждый основной абзац должен поддерживать её.', 'В выводе повтори тот же ответ без новой идеи.'], 'Не прячь своё мнение до последнего абзаца.', 'Проверяющий сразу видит твою позицию.'),
    kk: card('Пікір эссесі', 'Agree / disagree', 'Келісетініңді не келіспейтініңді бірден айт.', ['Пікір таңда: толық, жартылай келісемін немесе келіспеймін.', 'Осы пікірді кіріспеде қарапайым сөзбен жаз.', 'Әр негізгі абзац сол пікірді қолдасын.', 'Қорытындыда жаңа ойсыз сол жауапты қайтала.'], 'Пікіріңді соңғы абзацқа дейін жасырма.', 'Тексеруші сенің пікіріңді бірден көреді.'),
    en: card('Opinion essay', 'Agree / disagree', 'Say at once if you agree or disagree.', ['Choose a position: fully agree, partly agree, or disagree.', 'Write it in simple words in the introduction.', 'Make every body paragraph support it.', 'Repeat the same answer in the conclusion with no new idea.'], 'Do not hide your view until the final paragraph.', 'The examiner can see your position at once.'),
  },
  'w-discussion': {
    ru: card('Две позиции и твоё мнение', 'Discuss both views', 'Объясни обе стороны и выбери свою.', ['Коротко запиши причину для каждой стороны.', 'Во вступлении покажи своё мнение.', 'Дай каждой стороне отдельный основной абзац.', 'Сравни их по одному ясному правилу и сделай вывод.'], 'Фраза «обе стороны хороши» не показывает твоё мнение.', 'Обе стороны объяснены, и твой выбор понятен.'),
    kk: card('Екі пікір және сенің ойың', 'Discuss both views', 'Екі жақты түсіндіріп, өз таңдауыңды айт.', ['Әр жаққа бір себептен қысқа жаз.', 'Кіріспеде өз пікіріңді көрсет.', 'Әр пікірге бөлек негізгі абзац бер.', 'Оларды бір анық өлшеммен салыстырып, қорытынды жаса.'], '«Екі жақ та жақсы» деген сөз сенің пікіріңді көрсетпейді.', 'Екі жақ та түсіндірілген және сенің таңдауың анық.'),
    en: card('Two views and your opinion', 'Discuss both views', 'Explain both sides and choose your view.', ['Write one short reason for each side.', 'Show your own view in the introduction.', 'Give each view its own body paragraph.', 'Compare them with one clear rule and conclude.'], '“Both sides are good” does not show your opinion.', 'Both views are explained and your choice is clear.'),
  },
  'w-advantages': {
    ru: card('Плюсы и минусы', 'Advantages / disadvantages', 'Объясни пользу, вред и что важнее.', ['Проверь, просит ли вопрос только назвать стороны или сравнить их.', 'Выбери самые важные плюс и минус.', 'Объясни, кого они затрагивают и насколько сильно.', 'Если есть outweigh, прямо скажи, что важнее и почему.'], 'Два слабых плюса не всегда сильнее одного большого минуса.', 'Вывод сравнивает силу идей, а не только их количество.'),
    kk: card('Артықшылық пен кемшілік', 'Advantages / disadvantages', 'Пайдасын, зиянын және қайсысы маңызды екенін түсіндір.', ['Сұрақ тек екі жақты атауды ма, әлде салыстыруды ма сұрайды — тексер.', 'Ең маңызды бір плюс пен бір минусты таңда.', 'Олар кімге және қаншалық әсер ететінін түсіндір.', 'Outweigh болса, қайсысы маңызды екенін және неге екенін тура айт.'], 'Екі әлсіз пайда бір үлкен зияннан күшті болмауы мүмкін.', 'Қорытынды ой саны емес, олардың күшін салыстырады.'),
    en: card('Benefits and problems', 'Advantages / disadvantages', 'Explain the good side, bad side, and which matters more.', ['Check if the task asks you to list or to compare.', 'Choose the most important benefit and problem.', 'Explain who they affect and how strongly.', 'If the task says outweigh, state which side is stronger and why.'], 'Two weak benefits may not beat one serious problem.', 'The conclusion compares the strength, not just the number, of ideas.'),
  },
  'w-problem': {
    ru: card('Проблема, причина и решение', 'Problems / causes / solutions', 'Покажи, почему проблема появилась и как её исправить.', ['Раздели слова problem, cause и solution в самом вопросе.', 'Для причины объясни цепочку: что вызывает что.', 'Для решения назови конкретное действие и того, кто его сделает.', 'Покажи, как это действие убирает названную причину.'], '«Власти должны решить проблему» — это ещё не решение.', 'Каждое решение отвечает на конкретную причину.'),
    kk: card('Мәселе, себеп және шешім', 'Problems / causes / solutions', 'Мәселе неге шыққанын және оны қалай шешуді көрсет.', ['Сұрақтағы problem, cause және solution сөздерін бөлек белгіле.', 'Себеп үшін не нені тудыратынын түсіндір.', 'Шешім үшін нақты әрекет пен оны кім жасайтынын айт.', 'Бұл әрекет аталған себепті қалай азайтатынын көрсет.'], '«Үкімет шешуі керек» деген сөз әлі нақты шешім емес.', 'Әр шешім нақты бір себепке жауап береді.'),
    en: card('Problem, cause, and solution', 'Problems / causes / solutions', 'Show why a problem exists and how to fix it.', ['Mark problem, cause, and solution separately in the task.', 'For a cause, explain what leads to what.', 'For a solution, name one action and who will do it.', 'Show how that action removes the cause.'], '“The government should solve it” is not a full solution.', 'Every solution answers one clear cause.'),
  },
  'w-two-question': {
    ru: card('Два прямых вопроса', 'Two-part question', 'Нужно дать два отдельных ответа.', ['Перепиши два вопроса короткими словами.', 'Дай прямой ответ на каждый ещё в плане.', 'Посвяти каждому вопросу отдельный основной абзац.', 'В выводе коротко ответь на оба ещё раз.'], 'Сильный первый ответ не заменяет пропущенный второй.', 'Напротив каждого вопроса можно поставить галочку.'),
    kk: card('Екі тікелей сұрақ', 'Two-part question', 'Екі бөлек жауап беру керек.', ['Екі сұрақты қысқа сөзбен қайта жаз.', 'Жоспарда әр сұраққа тура жауап бер.', 'Әр сұраққа бөлек негізгі абзац арна.', 'Қорытындыда екеуіне де қысқа қайта жауап бер.'], 'Бірінші мықты жауап екінші бос жауаптың орнын толтырмайды.', 'Әр сұрақтың жанында жауап бар деп белгі қоя аласың.'),
    en: card('Two direct questions', 'Two-part question', 'Give two separate answers.', ['Rewrite both questions in short words.', 'Answer each one directly in your plan.', 'Give each question its own body paragraph.', 'Answer both again briefly in the conclusion.'], 'A strong first answer cannot replace a missing second answer.', 'You can tick off both questions as answered.'),
  },
  'w-paragraph': {
    ru: card('Сильный основной абзац', 'Идея → почему → пример → итог', 'Один абзац должен доказывать одну мысль.', ['Начни с одной ясной главной мысли.', 'Объясни, почему или как она работает.', 'Добавь короткий и подходящий пример.', 'Свяжи пример с вопросом одним итоговым предложением.'], 'Пример без объяснения не доказывает мысль.', 'Все предложения помогают одной главной идее.'),
    kk: card('Мықты негізгі абзац', 'Ой → неге → мысал → нәтиже', 'Бір абзац бір ойды дәлелдеуі керек.', ['Бір анық негізгі ойдан баста.', 'Оның неге немесе қалай жұмыс істейтінін түсіндір.', 'Қысқа әрі лайық мысал қос.', 'Мысалды сұрақпен бір қорытынды сөйлем арқылы байланыстыр.'], 'Түсіндірмесіз мысал ойды дәлелдемейді.', 'Барлық сөйлем бір негізгі ойға көмектеседі.'),
    en: card('Strong body paragraph', 'Idea → why → example → result', 'One paragraph should prove one idea.', ['Start with one clear main idea.', 'Explain why or how it works.', 'Add one short and fitting example.', 'Link the example back to the question.'], 'An example without an explanation does not prove the idea.', 'Every sentence supports the same main idea.'),
  },
  'w-language': {
    ru: card('Простые слова и точные предложения', 'Ясность важнее редких слов', 'Пиши так, чтобы смысл был понятен с первого раза.', ['Сначала напиши короткое предложение: кто делает что.', 'Добавляй сложную часть только после ясной основы.', 'Используй слово, значение которого точно знаешь.', 'В конце найди свои частые ошибки: артикль, -s, время и запятая.'], 'Заученные красивые фразы часто не подходят к вопросу.', 'Каждое предложение имеет подлежащее, глагол и ясный смысл.'),
    kk: card('Оңай сөз және нақты сөйлем', 'Түсініктілік сирек сөзден маңызды', 'Мағынасы бірінші оқығанда түсінікті болсын.', ['Алдымен қысқа сөйлем жаз: кім не істейді.', 'Күрделі бөлікті анық негізден кейін ғана қос.', 'Мағынасын нақты білетін сөзді қолдан.', 'Соңында жиі қателеріңді тексер: артикль, -s, шақ және үтір.'], 'Жатталған әдемі сөйлемдер сұраққа сай келмеуі мүмкін.', 'Әр сөйлемде бастауыш, етістік және анық мағына бар.'),
    en: card('Simple words and clear sentences', 'Clear is better than rare', 'Write so the meaning is clear on the first read.', ['Start with a short sentence: who does what.', 'Add a harder part only after the clear base.', 'Use a word only when you know its exact meaning.', 'Check your common errors: articles, -s, tense, and commas.'], 'Memorised fancy phrases often do not fit the question.', 'Every sentence has a subject, a verb, and a clear meaning.'),
  },

  's-cycle': {
    ru: card('Главная тренировка', 'Запиши · послушай · повтори', 'Этот цикл помогает заметить и исправить ошибки.', ['Запиши один ответ без остановки.', 'Прослушай и выбери только три главные ошибки.', 'Запиши три более ясные фразы.', 'Ответь на тот же вопрос ещё раз без чтения.'], 'Не учи весь ответ наизусть.', 'Вторая запись яснее и свободнее первой.'),
    kk: card('Негізгі жаттығу', 'Жаз · тыңда · қайтала', 'Бұл айналым қатені көруге және түзетуге көмектеседі.', ['Бір жауапты тоқтамай жазып ал.', 'Тыңдап, тек үш басты қатені таңда.', 'Үш анық сөйлемді қайта жаз.', 'Сол сұраққа қағаздан оқымай тағы жауап бер.'], 'Бүкіл жауапты жаттап алма.', 'Екінші жазба біріншіден анық және еркін.'),
    en: card('Main practice loop', 'Record · listen · repeat', 'This loop helps you notice and fix mistakes.', ['Record one answer without stopping.', 'Listen and choose only three main problems.', 'Write three clearer phrases.', 'Answer the same question again without reading.'], 'Do not memorise the whole answer.', 'The second recording is clearer and freer than the first.'),
  },
  's-part1': {
    ru: card('Part 1', 'Короткие вопросы о тебе', 'Дай прямой ответ и одну полезную деталь.', ['Ответь в первой фразе.', 'Добавь причину, пример или короткую историю.', 'Обычно говори 2–4 предложения.', 'Если вопрос простой, не превращай ответ в длинную речь.'], 'Ответ только yes или no слишком короткий.', 'Ответ прямой, личный и легко понятный.'),
    kk: card('Part 1', 'Өзің туралы қысқа сұрақтар', 'Тура жауап беріп, бір пайдалы мәлімет қос.', ['Бірінші сөйлемде жауап бер.', 'Себеп, мысал немесе қысқа оқиға қос.', 'Көбіне 2–4 сөйлем айт.', 'Оңай сұраққа өте ұзақ жауап берме.'], 'Тек yes немесе no деу тым қысқа.', 'Жауап тура, жеке және түсінікті.'),
    en: card('Part 1', 'Short questions about you', 'Answer directly and add one useful detail.', ['Give the answer in your first sentence.', 'Add a reason, example, or short story.', 'Usually speak for 2–4 sentences.', 'Do not turn a simple question into a long speech.'], 'Only yes or no is too short.', 'The answer is direct, personal, and easy to follow.'),
  },
  's-part2-plan': {
    ru: card('Part 2: одна минута на план', 'План карточки', 'Подготовь ключевые слова, а не полный текст.', ['Обведи тему и четыре пункта карточки.', 'Запиши 1–2 слова для каждого пункта.', 'Добавь одну историю с местом, временем и человеком.', 'Оставь последнее слово для вывода или чувства.'], 'Полные предложения в плане отнимают время и заставляют читать.', 'По коротким словам ты можешь говорить 1–2 минуты.'),
    kk: card('Part 2: жоспарға бір минут', 'Карточка жоспары', 'Толық мәтін емес, тірек сөздер жаз.', ['Тақырып пен төрт тармақты белгіле.', 'Әр тармаққа 1–2 сөз жаз.', 'Орын, уақыт және адам бар бір оқиға қос.', 'Соңғы сөзді қорытынды не сезім үшін қалдыр.'], 'Толық сөйлем жазу уақыт алады және оқуға мәжбүр етеді.', 'Қысқа сөздерге қарап 1–2 минут сөйлей аласың.'),
    en: card('Part 2: one-minute plan', 'Cue card plan', 'Write key words, not a full speech.', ['Circle the topic and the four card points.', 'Write 1–2 words for each point.', 'Add one story with a place, time, and person.', 'Keep one final word for a result or feeling.'], 'Full sentences take time and make you read.', 'Your short notes help you speak for 1–2 minutes.'),
  },
  's-part2-talk': {
    ru: card('Part 2: длинный ответ', 'До двух минут', 'Расскажи одну понятную историю по карточке.', ['Начни с прямого ответа и места или времени.', 'Двигайся по плану и раскрывай каждый пункт.', 'Добавляй детали: что случилось, почему и что ты почувствовал.', 'Заверши коротким итогом, когда идеи закончились.'], 'Не повторяй один пункт разными словами ради времени.', 'Ответ имеет начало, развитие и ясный конец.'),
    kk: card('Part 2: ұзақ жауап', 'Екі минутқа дейін', 'Карточка бойынша бір түсінікті оқиға айт.', ['Тура жауаптан және орыннан не уақыттан баста.', 'Жоспар бойынша жүріп, әр тармақты аш.', 'Не болды, неге болды және не сездің — мәлімет қос.', 'Ой біткенде қысқа қорытындымен аяқта.'], 'Уақыт үшін бір ойды қайта-қайта айтпа.', 'Жауаптың басы, дамуы және анық соңы бар.'),
    en: card('Part 2: long answer', 'Up to two minutes', 'Tell one clear story from the card.', ['Start with a direct answer and a place or time.', 'Follow your plan and cover each card point.', 'Add details: what happened, why, and how you felt.', 'Finish with a short result when your ideas end.'], 'Do not repeat one point only to fill time.', 'The answer has a start, development, and clear end.'),
  },
  's-part3': {
    ru: card('Part 3', 'Большие вопросы и идеи', 'Дай мнение, причину и пример.', ['Скажи свой главный ответ в первой фразе.', 'Объясни, почему это происходит.', 'Добавь пример общества, школы, семьи или страны.', 'Если нужно, покажи другую сторону словами however или it depends.'], 'Здесь не ищут единственно правильное мнение.', 'Ответ имеет мнение, причину и пример.'),
    kk: card('Part 3', 'Үлкен сұрақтар мен ойлар', 'Пікір, себеп және мысал бер.', ['Негізгі жауабыңды бірінші сөйлемде айт.', 'Неге бұлай болатынын түсіндір.', 'Қоғамнан, мектептен, отбасынан не елден мысал қос.', 'Керек болса, however немесе it depends деп екінші жағын көрсет.'], 'Мұнда жалғыз дұрыс пікір ізделмейді.', 'Жауапта пікір, себеп және мысал бар.'),
    en: card('Part 3', 'Big questions and ideas', 'Give a view, a reason, and an example.', ['State your main answer in the first sentence.', 'Explain why it happens.', 'Add an example from society, school, family, or a country.', 'If useful, show another side with however or it depends.'], 'There is no single correct opinion.', 'The answer has a view, a reason, and an example.'),
  },
  's-fluency': {
    ru: card('Темп и паузы', 'Говори ровно', 'Короткие паузы между мыслями — это нормально.', ['Говори чуть медленнее, чем хочется.', 'Делай паузу после законченной идеи, не внутри фразы.', 'Забыл слово — объясни его простыми словами.', 'В записи отметь только паузы длиннее двух секунд.'], 'Очень быстрая речь с обрывами не звучит свободно.', 'Главные слова слышны, а паузы стоят между мыслями.'),
    kk: card('Қарқын мен үзіліс', 'Бірқалыпты сөйле', 'Ойлардың арасындағы қысқа үзіліс қалыпты.', ['Қалағаныңнан сәл баяу сөйле.', 'Сөйлемнің ішінде емес, ой аяқталғанда кідір.', 'Сөзді ұмытсаң, оны оңай сөзбен түсіндір.', 'Жазбада екі секундтан ұзақ үзілісті ғана белгіле.'], 'Үзіліп тұрған өте жылдам сөз еркін естілмейді.', 'Негізгі сөздер анық, үзіліс ойлардың арасында тұр.'),
    en: card('Speed and pauses', 'Speak at a steady pace', 'Short pauses between ideas are normal.', ['Speak a little slower than you want to.', 'Pause after a finished idea, not inside a phrase.', 'If you forget a word, explain it with simple words.', 'In a recording, mark only pauses longer than two seconds.'], 'Very fast speech with broken phrases is not fluent.', 'Key words are clear and pauses come between ideas.'),
  },
  's-correction': {
    ru: card('Как исправлять себя', 'Быстро и спокойно', 'Исправляй только ошибку, которая мешает смыслу.', ['Если смысл изменился, скажи sorry, I mean… и исправь.', 'После исправления сразу продолжай ответ.', 'Маленькую ошибку лучше оставить, чем остановиться надолго.', 'После тренировки выпиши ошибку и повтори фразу.'], 'Исправление каждого слова ломает темп.', 'Исправление заняло одну короткую фразу.'),
    kk: card('Өзіңді қалай түзету керек', 'Тез және тыныш', 'Мағынаға кедергі жасайтын қатені ғана түзет.', ['Мағына өзгерсе, sorry, I mean… деп түзет.', 'Түзеткеннен кейін жауапты бірден жалғастыр.', 'Кішкентай қатені ұзақ тоқтағаннан гөрі қалдырған дұрыс.', 'Жаттығудан кейін қатені жазып, сөйлемді қайтала.'], 'Әр сөзді түзету сөйлеу қарқынын бұзады.', 'Түзету бір қысқа сөйлемге ғана созылды.'),
    en: card('How to correct yourself', 'Quick and calm', 'Correct only a mistake that hurts the meaning.', ['If the meaning changed, say sorry, I mean… and correct it.', 'Continue the answer at once.', 'Leave a small error instead of stopping for a long time.', 'After practice, write the error and repeat the sentence.'], 'Correcting every word breaks your speaking flow.', 'The correction took only one short phrase.'),
  },
  's-unknown': {
    ru: card('Незнакомая тема', 'Как продолжить ответ', 'Можно рассуждать, даже если у тебя нет опыта.', ['Скажи честно: I haven’t thought about this, but…', 'Возьми похожий пример, который ты знаешь.', 'Сделай простое предположение: I suppose…', 'Продолжи ответ причиной и примером.'], 'Фраза I don’t know без продолжения обрывает ответ.', 'Даже без опыта у тебя есть мнение, причина и пример.'),
    kk: card('Бейтаныс тақырып', 'Жауапты қалай жалғастыру керек', 'Тәжірибең болмаса да, ой айта аласың.', ['I haven’t thought about this, but… деп шын айт.', 'Өзің білетін ұқсас мысалды ал.', 'I suppose… деп қарапайым болжам жаса.', 'Себеп пен мысал арқылы жауапты жалғастыр.'], 'I don’t know деп тоқтау жауапты үзіп тастайды.', 'Тәжірибесіз де пікір, себеп және мысал айта аласың.'),
    en: card('Unknown topic', 'How to keep answering', 'You can think aloud even without experience.', ['Say honestly: I haven’t thought about this, but…', 'Use a similar example that you know.', 'Make a simple guess with I suppose…', 'Continue with a reason and example.'], 'I don’t know with nothing more ends the answer.', 'Even without experience, you give a view, reason, and example.'),
  },
  's-linking': {
    ru: card('Связная речь', 'Естественные связи', 'Связывай идеи простыми словами.', ['Для причины используй because или so.', 'Для примера используй for example.', 'Для другой стороны используй but, however или at the same time.', 'Не ставь связку в каждое предложение.'], 'Firstly, secondly и moreover в каждом ответе звучат как заученный текст.', 'Каждая связка показывает настоящую связь между мыслями.'),
    kk: card('Байланысты сөйлеу', 'Табиғи байланыстар', 'Ойларды оңай сөзбен байланыстыр.', ['Себеп үшін because немесе so қолдан.', 'Мысал үшін for example қолдан.', 'Басқа жақ үшін but, however немесе at the same time қолдан.', 'Әр сөйлемге байланыс сөзін қойма.'], 'Әр жауаптағы firstly, secondly, moreover жатталған мәтіндей естіледі.', 'Әр байланыс сөзі ойлардың шын байланысын көрсетеді.'),
    en: card('Connected speech', 'Natural links', 'Connect ideas with simple words.', ['Use because or so for a reason.', 'Use for example for an example.', 'Use but, however, or at the same time for another side.', 'Do not add a link word to every sentence.'], 'Firstly, secondly, and moreover in every answer sound memorised.', 'Every link word shows a real link between ideas.'),
  },
  's-examiner': {
    ru: card('Как говорить с экзаменатором', 'Если не понял вопрос', 'Можно спокойно попросить повторить вопрос.', ['Не расслышал: Could you repeat the question, please?', 'В Part 3 можно попросить объяснить вопрос другими словами.', 'После повтора сразу дай прямой ответ.', 'Если тебя остановили, это обычно значит, что время закончилось.'], 'Угаданный вопрос ведёт к длинному ответу не по теме.', 'После уточнения ты отвечаешь именно на вопрос.'),
    kk: card('Емтихан алушымен сөйлесу', 'Сұрақты түсінбесең', 'Сұрақты қайталауды тыныш сұрауға болады.', ['Естімесең: Could you repeat the question, please?', 'Part 3-те сұрақты басқа сөзбен түсіндіруді сұрай аласың.', 'Қайталағаннан кейін бірден тура жауап бер.', 'Сені тоқтатса, көбіне бөлімнің уақыты біткен.'], 'Сұрақты болжау тақырыптан тыс ұзақ жауапқа әкеледі.', 'Түсіндіргеннен кейін дәл сол сұраққа жауап бересің.'),
    en: card('Talking to the examiner', 'If you do not understand', 'You may calmly ask for the question again.', ['If you did not hear: Could you repeat the question, please?', 'In Part 3, you may ask for the question in other words.', 'After the repeat, give a direct answer.', 'If you are stopped, the part has usually run out of time.'], 'Guessing the question can lead to a long answer about the wrong topic.', 'After help, you answer the exact question.'),
  },
};

export function getSectionText(section: GuideSection, language: CourseLanguage): SectionText {
  return sections[section.id][language];
}

export function getCardText(source: GuideCard, language: CourseLanguage): GuideCard {
  return { id: source.id, ...(cards[source.id]?.[language] ?? source) };
}

export function getDateLocale(language: CourseLanguage) {
  return language === 'kk' ? 'kk-KZ' : language === 'en' ? 'en-GB' : 'ru-RU';
}

const kkMonths = ['қаңтар', 'ақпан', 'наурыз', 'сәуір', 'мамыр', 'маусым', 'шілде', 'тамыз', 'қыркүйек', 'қазан', 'қараша', 'желтоқсан'];
const kkWeekdays = ['дс', 'сс', 'ср', 'бс', 'жм', 'сб', 'жс'];
const kkWeekdaysNarrow = ['Ж', 'Д', 'С', 'С', 'Б', 'Ж', 'С'];

export function getMonthLabel(date: Date, language: CourseLanguage) {
  if (language === 'kk') return `${kkMonths[date.getMonth()]} ${date.getFullYear()}`;
  return new Intl.DateTimeFormat(getDateLocale(language), { month: 'long', year: 'numeric' }).format(date);
}

export function getCalendarWeekdays(language: CourseLanguage) {
  if (language === 'kk') return kkWeekdays;
  return Array.from({ length: 7 }, (_, index) => new Intl.DateTimeFormat(getDateLocale(language), { weekday: 'short' }).format(new Date(2026, 0, 5 + index)));
}

export function getNarrowWeekday(date: Date, language: CourseLanguage) {
  if (language === 'kk') return kkWeekdaysNarrow[date.getDay()];
  return new Intl.DateTimeFormat(getDateLocale(language), { weekday: 'narrow' }).format(date);
}
